apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vpm3jp94u-python
  janus-idp.io/tekton: vpm3jp94u-python
  backstage.io/kubernetes-id: vpm3jp94u-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vpm3jp94u-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
