apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: vpm3jp94u-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vpm3jp94u-python 
  name: vpm3jp94u-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: vpm3jp94u-python
    weight: 100 
